[package]
name = "impostare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
postgres = "0.19.7"
serde = { version = "1.0.198", features = ["derive"] }
toml = "0.8.12"
