[[databases]]
name = "metrics"

[[extensions]]
name = "timescaledb"
database = "metrics"

[[users]]
name = "grafana"
password_file = "${CREDENTIALS_DIRECTORY}/postgres-password-grafana"

[[users]]
name = "telegraf"
password_file = "${CREDENTIALS_DIRECTORY}/postgres-password-telegraph"

[[database_permissions]]
role = "telegraf"
permissions = ["CONNECT"]
databases = ["metrics"]

[[schema_permissions]]
role = "telegraf"
permissions = ["CREATE"]
database = "metrics"
schemas = ["public"]
make_default = true

[[table_permissions]]
role = "telegraf"
permissions = ["ALL"]
database = "metrics"
tables = "ALL"
make_default = true

[[table_permissions]]
role = "grafana"
permissions = ["SELECT"]
database = "metrics"
tables = "ALL"
make_default = true
