[[databases]]
name = "metrics"
extensions = ["timescaledb"]

[[users]]
name = "grafana"
password_file = "${CREDENTIALS_DIRECTORY}/postgres-password-grafana"

[[users]]
name = "telegraf"
password_file = "${CREDENTIALS_DIRECTORY}/postgres-password-telegraph"

[[database_permissions]]
role = "telegraf"
permissions = ["CONNECT"]
databases = ["metrics"]
make_default = true

[[schema_permissions]]
role = "telegraf"
permissions = ["CREATE"]
schemas = ["metrics.public"]
make_default = true

[[table_permissions]]
role = "telegraf"
permissions = ["ALL"]
tables = "ALL"
make_default = true

[[table_permissions]]
role = "grafana"
permissions = ["SELECT"]
tables = "ALL"
make_default = true
